name: Learning github actions

on: [push]

env:
  DBLINK: cyusa

jobs:
  output_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Output my name
        run: 
          echo $DBLINK
      - name: Check in names
        run: 
          echo ${{secrets.NAME}}